package org.invik.corsaircuejna.jna;
import org.invik.corsaircuejna.jna.CorsairCUEJNAWrapperLibrary.CorsairLedId;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * contains led id and position of led rectangle.Most of the keys are rectangular.In case if key is not rectangular(like Enter in ISO / UK layout) it returns the smallest rectangle that fully contains the key<br>
 * <i>native declaration : include\CUESDK.h:82</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("CorsairCUEJNAWrapper.x64_2013")
public class JNACorsairLedPosition extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * identifier of led<br>
	 * C type : CorsairLedId
	 */
	@Field(0) 
	public IntValuedEnum<CorsairLedId > ledId() {
		return this.io.getEnumField(this, 0);
	}
	/**
	 * identifier of led<br>
	 * C type : CorsairLedId
	 */
	@Field(0) 
	public JNACorsairLedPosition ledId(IntValuedEnum<CorsairLedId > ledId) {
		this.io.setEnumField(this, 0, ledId);
		return this;
	}
	@Field(1) 
	public double top() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public JNACorsairLedPosition top(double top) {
		this.io.setDoubleField(this, 1, top);
		return this;
	}
	@Field(2) 
	public double left() {
		return this.io.getDoubleField(this, 2);
	}
	@Field(2) 
	public JNACorsairLedPosition left(double left) {
		this.io.setDoubleField(this, 2, left);
		return this;
	}
	@Field(3) 
	public double height() {
		return this.io.getDoubleField(this, 3);
	}
	@Field(3) 
	public JNACorsairLedPosition height(double height) {
		this.io.setDoubleField(this, 3, height);
		return this;
	}
	/** values in mm */
	@Field(4) 
	public double width() {
		return this.io.getDoubleField(this, 4);
	}
	/** values in mm */
	@Field(4) 
	public JNACorsairLedPosition width(double width) {
		this.io.setDoubleField(this, 4, width);
		return this;
	}
	public JNACorsairLedPosition() {
		super();
	}
	public JNACorsairLedPosition(Pointer pointer) {
		super(pointer);
	}


}
