package org.invik.corsaircuejna.jna;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * contains information about led and its color<br>
 * <i>native declaration : include\CUESDK.h:97</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("CorsairCUEJNAWrapper.x64_2013")
public class JNACorsairLedColor extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * identifier of LED to set<br>
	 * C type : CorsairLedId
	 */
	@Field(0) 
	public IntValuedEnum<CorsairCUEJNAWrapperLibrary.CorsairLedId> ledId() {
		return this.io.getEnumField(this, 0);
	}
	/**
	 * identifier of LED to set<br>
	 * C type : CorsairLedId
	 */
	@Field(0) 
	public JNACorsairLedColor ledId(IntValuedEnum<CorsairCUEJNAWrapperLibrary.CorsairLedId> ledId) {
		this.io.setEnumField(this, 0, ledId);
		return this;
	}
	/** red   brightness[0..255] */
	@Field(1) 
	public int r() {
		return this.io.getIntField(this, 1);
	}
	/** red   brightness[0..255] */
	@Field(1) 
	public JNACorsairLedColor r(int r) {
		this.io.setIntField(this, 1, r);
		return this;
	}
	/** green brightness[0..255] */
	@Field(2) 
	public int g() {
		return this.io.getIntField(this, 2);
	}
	/** green brightness[0..255] */
	@Field(2) 
	public JNACorsairLedColor g(int g) {
		this.io.setIntField(this, 2, g);
		return this;
	}
	/** blue  brightness[0..255] */
	@Field(3) 
	public int b() {
		return this.io.getIntField(this, 3);
	}
	/** blue  brightness[0..255] */
	@Field(3) 
	public JNACorsairLedColor b(int b) {
		this.io.setIntField(this, 3, b);
		return this;
	}
	public JNACorsairLedColor() {
		super();
	}
	public JNACorsairLedColor(Pointer pointer) {
		super(pointer);
	}
}
